apiVersion : apps/v1
kind: Deployment
metadata:
  name: "testcluster-b80a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "testcluster-b80a"
  template:
    metadata:
      labels:
        app: "testcluster-b80a"
    spec:
      containers:
        - name: "testcluster-b80a"
          image: "artiushenkoacr.azurecr.io/testcluster"
          ports:
          - containerPort: 80