name: CI

on:
  push:
    branches: [dev]
#    paths-ignore: 
#      - '.github/workflows/**'
  pull_request:
    branches: [release, main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_ZONE: europe   # TODO: update to cluster zone
  IMAGE: alpine_main

jobs:
  Setup-build-publish:
    name: Setup, Build, Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get tags
      - name: Fetching tags
        if: ${{ github.base_ref == 'main' ||  github.base_ref == 'release' }}
        run: git fetch --tags

      # Setup gcloud CLI
      - uses:  google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: auth docker
        run: |
          gcloud auth configure-docker -q

      # Get image prefix
      - name: Image tag dev
        if: ${{ github.ref_name == 'dev' }}
        run: echo "IMAGE_TAG=dev-$(date +'%s')" >> $GITHUB_ENV

      - name: Image tag release
        if: ${{ github.base_ref == 'release' }}
        run: echo "IMAGE_TAG=$((git tag | egrep rc-[0-9] || echo rc-0 ) | sort --version-sort -r | head -1 | awk -F 'rc-' '{ print "rc-" $2 +1}')" >> $GITHUB_ENV

      - name: Image tag version
        if: ${{ github.base_ref == 'main' }}
        run: echo "IMAGE_TAG=$((git tag | egrep v[0-9]\.[0-9]\.[0-9] || echo v1.0.-1 ) | sort --version-sort -r | head -1 | awk -F. -v OFS=. '{$NF++;print}')" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # On failed build send message to slack shannel
      - name: Sending failed message
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Build failed ${{ env.IMAGE_TAG }}"
          SLACK_COLOR: ${{ job.status }}

      # On success
      - name: Sending success message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Build successful ${{ env.IMAGE_TAG }}"
          SLACK_COLOR: ${{ job.status }}

      # After successful build add tag
      - name: Update release number
        if: ${{ github.base_ref == 'main' ||  github.base_ref == 'release' }}
        run: |-
          git tag $IMAGE_TAG && git push --tags

      # Push the Docker image to Google Container Registry
      - name: Publish
        uses: ./.github/workflows/push-to-gcr-action
        with: 
          project-id: $PROJECT_ID
          image: $IMAGE
          tag:  $IMAGE_TAG