on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: artiushenkoacr.azurecr.io
        username: ${{ secrets.acr_artiushenkoacr_username }}
        password: ${{ secrets.acr_artiushenkoacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t artiushenkoacr.azurecr.io/testcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push artiushenkoacr.azurecr.io/testcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testclusterb9d6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testclusterb9d6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testclusterb9d6
        container-registry-url: artiushenkoacr.azurecr.io
        container-registry-username: ${{ secrets.acr_artiushenkoacr_username }}
        container-registry-password: ${{ secrets.acr_artiushenkoacr_password }}
        secret-name: testclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testclusterb9d6
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          artiushenkoacr.azurecr.io/testcluster:${{ github.sha }}
        imagepullsecrets: |
          testclusterdockerauth
